services:
  config-0:
    image: my-mongo:${MONGO_VER}
    build: 
      context: mongodb-build
      args:
        - MONGO_VER=${MONGO_VER}
    container_name: config-0
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/config-0/db:/data/db
      - ${MONGO_PATH}/config-0/configdb:/data/configdb
    ports:
      - 27018:27017
    restart: always
    entrypoint: ["mongod", "--port", "27017", "--configsvr", "--replSet", "config-rs", "--bind_ip_all", "--keyFile", "/data/mongodb-keyfile"]
  shard-0:
    image: my-mongo:${MONGO_VER}
    depends_on:
      - config-0
    links:
      - config-0
    container_name: shard-0
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/shard-0/db:/data/db
      - ${MONGO_PATH}/shard-0/configdb:/data/configdb
    ports:
      - 27019:27017
    restart: always
    entrypoint: ["mongod", "--port", "27017", "--shardsvr", "--replSet", "shard-rs-0", "--bind_ip_all", "--keyFile", "/data/mongodb-keyfile"]
  shard-1:
    image: my-mongo:${MONGO_VER}
    depends_on:
      - config-0
    links:
      - config-0
    container_name: shard-1
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/shard-1/db:/data/db
      - ${MONGO_PATH}/shard-1/configdb:/data/configdb
    ports:
      - 27020:27017
    restart: always
    entrypoint: ["mongod", "--port", "27017", "--shardsvr", "--replSet", "shard-rs-1", "--bind_ip_all", "--keyFile", "/data/mongodb-keyfile"]
  router-0:
    image: my-mongo:${MONGO_VER}
    depends_on:
      - config-0
    container_name: router-0
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/router-0/db:/data/db
      - ${MONGO_PATH}/router-0/configdb:/data/configdb
    ports:
      - 27017:27017
    restart: always
    entrypoint: ["mongos", "--port", "27017", "--configdb", "config-rs/config-0:27017", "--bind_ip_all", "--keyFile", "/data/mongodb-keyfile"]
