services:
  shard-0:
    image: mongo:${MONGO_VER}
    container_name: shard-0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/shard-0/db:/data/db
      - ${MONGO_PATH}/shard-0/configdb:/data/configdb
    ports:
      - 27017:27017
    entrypoint: ["mongod", "--port", "27017", "--shardsvr", "--replSet", "shard-rs-0", "--bind_ip_all"]
  shard-1:
    image: mongo:${MONGO_VER}
    container_name: shard-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/shard-1/db:/data/db
      - ${MONGO_PATH}/shard-1/configdb:/data/configdb
    ports:
      - 27018:27017
    entrypoint: ["mongod", "--port", "27017", "--shardsvr", "--replSet", "shard-rs-1", "--bind_ip_all"]
  config-0:
    image: mongo:${MONGO_VER}
    container_name: config-0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/config-0/db:/data/db
      - ${MONGO_PATH}/config-0/configdb:/data/configdb
    ports:
      - 27019:27017
    entrypoint: ["mongod", "--port", "27017", "--configsvr", "--replSet", "config-rs", "--bind_ip_all"]
    links:
      - shard-0
      - shard-1
  router-0:
    image: mongo:${MONGO_VER}
    container_name: router-0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/router-0/db:/data/db
      - ${MONGO_PATH}/router-0/configdb:/data/configdb
    ports:
      - 27020:27017
    entrypoint: ["mongos", "--port", "27017", "--configdb", "config-rs/config-0:27017", "--bind_ip_all"]
