services:
  config-0:
    image: my-mongo:${MONGO_VER}
    build: 
      context: mongodb-build
      args:
        - MONGO_VER=${MONGO_VER}
    container_name: ${CONFIG_0}
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/${CONFIG_0}/db:/data/db
      - ${MONGO_PATH}/${CONFIG_0}/configdb:/data/configdb
    ports:
      - 27018:27017
    # restart: always
    command: mongod --port 27017 --configsvr --replSet ${CONFIG_RS} --bind_ip 0.0.0.0 --keyFile /data/mongodb-keyfile
    # entrypoint: ["mongod", "--port", "27017", "--configsvr", "--replSet", "config-rs", "--bind_ip", "0.0.0.0", "--keyFile", "/data/mongodb-keyfile"]
  shard-rs0-0:
    image: my-mongo:${MONGO_VER}
    depends_on:
      - ${CONFIG_0}
    container_name: ${SHARD_RS0_0}
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/${SHARD_RS0_0}/db:/data/db
      - ${MONGO_PATH}/${SHARD_RS0_0}/configdb:/data/configdb
    ports:
      - 27019:27017
    # restart: always
    command: mongod --port 27017 --shardsvr --replSet ${SHARD_RS0} --bind_ip 0.0.0.0 --keyFile /data/mongodb-keyfile
    # entrypoint: ["mongod", "--port", "27017", "--shardsvr", "--replSet", "shard-rs0", "--bind_ip", "0.0.0.0", "--keyFile", "/data/mongodb-keyfile"]
  shard-rs1-0:
    image: my-mongo:${MONGO_VER}
    depends_on:
      - ${CONFIG_0}
    container_name: shard-rs1-0
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/${SHARD_RS1_0}/db:/data/db
      - ${MONGO_PATH}/${SHARD_RS1_0}/configdb:/data/configdb
    ports:
      - 27020:27017
    # restart: always
    command: mongod --port 27017 --shardsvr --replSet ${SHARD_RS1} --bind_ip 0.0.0.0 --keyFile /data/mongodb-keyfile
    # entrypoint: ["mongod", "--port", "27017", "--shardsvr", "--replSet", "shard-rs1", "--bind_ip", "0.0.0.0", "--keyFile", "/data/mongodb-keyfile"]
  router-0:
    image: my-mongo:${MONGO_VER}
    depends_on:
      - ${SHARD_RS0_0}
      - ${SHARD_RS1_0}
    container_name: ${ROUTER_0}
    volumes:
      - ./scripts:/scripts
      - ${MONGO_PATH}/${ROUTER_0}/db:/data/db
      - ${MONGO_PATH}/${ROUTER_0}/configdb:/data/configdb
    ports:
      - 27017:27017
    # restart: always
    command: mongos --port 27017 --configdb ${CONFIG_RS}/${CONFIG_0}:27017 --bind_ip 0.0.0.0 --keyFile /data/mongodb-keyfile
    # entrypoint: ["mongos", "--port", "27017", "--configdb", "config-rs/config-0:27017", "--bind_ip", "0.0.0.0", "--keyFile", "/data/mongodb-keyfile"]
